DROP TABLE IF EXISTS song;

DROP TABLE IF EXISTS album;

DROP TABLE IF EXISTS artist;

CREATE TABLE
  `artist` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
  );

CREATE TABLE
  `album` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `artist_id` INT UNSIGNED NOT NULL,
    `img_src` VARCHAR(511) NOT NULL
  );

CREATE TABLE
  `song` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `artist_id` INT UNSIGNED NOT NULL,
    `src` VARCHAR(511) NOT NULL,
    `duration` INT UNSIGNED NOT NULL,
    `album_id` INT UNSIGNED NOT NULL,
    FOREIGN KEY (`album_id`) REFERENCES `album` (`id`)
  );

CREATE TABLE `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` TEXT NOT NULL,
    `superuser` BOOLEAN NOT NULL
);

