name: Vite Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: './frontend/package-lock.json'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: tree
        run: tree
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vite-artifact
          path: |
            frontend/dist/
